### ISSUE TITLE
Parallel Build Failures

### ISSUE THREAD

**Issue by TinoDidriksen** [apertium/organisation#2]
Downstream bug: https://bugs.debian.org/910045

Similar to https://github.com/apertium/apertium/commit/2c0e7e09b0ae5d158410773285ee3ae4f55cfe92 , https://github.com/apertium/apertium/commit/600c117389dec62d70b0f9a62771c6fecc24700e

If apertium and apertium-hbs-mkd did/does it wrong, it's probably something we need to check for all repos.

**Comment by kartikm** [comment]
@TinoDidriksen Should we patch it in Debian or just wait for new Apertium release?
