### ISSUE TITLE
Apertium morphology analysis tags parser

### ISSUE THREAD

**Issue by alexeyev** [apertium/organisation#33]
Hi, dear colleagues, thank you for your great work!

I hope I chose the right repo for this question.

Are you aware of any tool for parsing Apertium's morphological analysis output, say, in Python?

What I am hoping to do is to convert the output with the tags listed [here](https://wiki.apertium.org/wiki/%D0%A1%D0%BF%D0%B8%D1%81%D0%BE%D0%BA_%D1%81%D0%B8%D0%BC%D0%B2%D0%BE%D0%BB%D0%BE%D0%B2) to some Python objects.

```
$ echo "Бул кыргызча морфологиялык талдоо" | apertium -d . kir-morph

^Бул/бул<det><dem>/бул<prn><dem><nom>/бул<prn><dem><nom>+э<cop><aor><p3><pl>/бул<prn><dem><nom>+э<cop><aor><p3><sg>$ ^кыргызча/кыргызча<adv>/кыргызча<n><attr>/кыргызча<n><nom
>/кыргызча<n><nom>+э<cop><aor><p3><pl>/кыргызча<n><nom>+э<cop><aor><p3><sg>/кыргыз<n><equ>/кыргыз<n><equ>+э<cop><aor><p3><pl>/кыргыз<n><equ>+э<cop><aor><p3><sg>$ ^морфологиял
ык/морфологиялык<adj>/морфологиялык<adj>+э<cop><aor><p3><pl>/морфологиялык<adj>+э<cop><aor><p3><sg>$ ^талдоо/талда<v><tv><ger><nom>/талда<v><tv><ger><nom>+э<cop><aor><p3><pl>
/талда<v><tv><ger><nom>+э<cop><aor><p3><sg>$^./.<sent>$
```

Clearly, this is not a hard task, I just want to make sure nothing of the sort exists before I start coding something of my own :)

Thank you!

Best regards, Anton.

**Comment by TinoDidriksen** [comment]
https://github.com/apertium/streamparser

**Comment by alexeyev** [comment]
Seems to be what I was looking for. Thank you for the prompt response! @TinoDidriksen
