### ISSUE TITLE
Add apertium-cleanstream to the github repository

### ISSUE THREAD

**Issue by AMR-KELEG** [apertium/organisation#9]
The `apertium-cleanstream` needs to be added from the svn repository: http://svn.code.sf.net/p/apertium/svn/trunk/apertium-tools/apertium-cleanstream/ to github.

**Comment by TinoDidriksen** [comment]
@unhammer, has this been superceded by https://github.com/apertium/streamparser ?

**Comment by unhammer** [comment]
apertium-cleanstream is a simple, dependency-less C++ program, while streamparser is for when you want more control but also can depend on python (and can live with it being much slower), so I'd say it makes sense to add apertium-cleanstream to https://github.com/apertium/apertium – should fit nicely in there.
